#!/usr/bin/env node

/**
 * security-tier.mjs — EverClaw Security Tier Management
 *
 * Standalone CLI for configuring and inspecting OpenClaw's exec-approval
 * security tiers. Can be run post-install to change tiers or check status.
 *
 * Usage:
 *   node scripts/security-tier.mjs --status              # Show current tier & rules
 *   node scripts/security-tier.mjs --tier recommended     # Set tier (low|recommended|maximum)
 *   node scripts/security-tier.mjs --tier recommended --apply  # Set tier and write to disk
 *   node scripts/security-tier.mjs --help
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { platform } from "node:os";
import { resolveBins, getPlatformBins } from "./lib/detect-bins.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, "..", "templates");
const HOME = process.env.HOME || "";
const VALID_TIERS = ["low", "recommended", "maximum"];

// ─── Helpers ───────────────────────────────────────────────────

function getOpenClawDir() {
  const xdg = process.env.XDG_CONFIG_HOME ? join(process.env.XDG_CONFIG_HOME, "openclaw") : null;
  const candidates = [
    process.env.OPENCLAW_STATE_DIR,
    join(HOME, ".openclaw"),
    xdg,
    join(HOME, ".clawdbot"),
  ].filter(Boolean);
  for (const dir of candidates) {
    if (dir && existsSync(dir)) return dir;
  }
  return join(HOME, ".openclaw");
}

function loadTierTemplate(tier) {
  const file = `exec-approvals-${tier}.json`;
  const path = join(TEMPLATES_DIR, file);
  if (!existsSync(path)) {
    console.error(`  ❌ Template not found: ${path}`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, "utf-8"));
}

function createTimestamp() {
  return new Date().toISOString();
}

/**
 * Generate a complete exec-approvals.json from a tier template.
 * Resolves all binary names to actual paths on this system.
 */
function generateExecApprovals(template) {
  const allBins = getPlatformBins(template.bins, template.macBins || [], template.linuxBins || []);
  const { found, missing, warnings } = resolveBins(allBins, { verbose: true });

  if (warnings.length > 0) {
    console.log("");
    for (const w of warnings) {
      console.log(`  ⚠️  ${w}`);
    }
  }

  // Build allowlist entries
  const allowlist = found.map(({ name, path }) => ({
    pattern: path,
    _name: name,
  }));

  // Build the exec-approvals.json structure
  const approvals = {
    version: 1,
    generatedBy: "everclaw-setup-v1",
    generatedAt: createTimestamp(),
    tier: template.tier,
    tierLabel: template.label,
    defaults: {
      security: template.config.security,
      ask: template.config.ask,
      askFallback: template.config.askFallback,
      autoAllowSkills: template.config.autoAllowSkills,
    },
    agents: {
      main: {
        security: template.config.security,
        ask: template.config.ask,
        askFallback: template.config.askFallback,
        autoAllowSkills: template.config.autoAllowSkills,
        allowlist,
      },
    },
  };

  // Build the openclaw.json tools.exec patch
  const openclawPatch = {
    tools: {
      exec: {
        ask: template.config.ask,
        safeBins: template.config.safeBins,
        safeBinTrustedDirs: template.config.safeBinTrustedDirs,
        safeBinProfiles: template.config.safeBinProfiles,
        strictInlineEval: template.config.strictInlineEval,
      },
    },
  };

  return {
    approvals,
    openclawPatch,
    stats: {
      found: found.length,
      missing: missing.length,
      total: allBins.length,
    },
  };
}

/**
 * Deep-merge source into target (mutates target).
 * Arrays are replaced, not merged.
 */
function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (
      source[key] &&
      typeof source[key] === "object" &&
      !Array.isArray(source[key]) &&
      target[key] &&
      typeof target[key] === "object" &&
      !Array.isArray(target[key])
    ) {
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

/**
 * Write exec-approvals.json and patch openclaw.json.
 * Respects upgrade safety: only overwrites if generatedBy matches.
 */
function applyTier(generated, options = {}) {
  const { force = false, dryRun = false } = options;
  const openclawDir = getOpenClawDir();
  const approvalsPath = join(openclawDir, "exec-approvals.json");
  const configPath = join(openclawDir, "openclaw.json");

  // Upgrade safety check
  if (existsSync(approvalsPath) && !force) {
    const existing = JSON.parse(readFileSync(approvalsPath, "utf-8"));
    if (existing.generatedBy && existing.generatedBy !== "everclaw-setup-v1") {
      console.log(`\n  ⚠️  exec-approvals.json was generated by: ${existing.generatedBy}`);
      console.log("  Skipping overwrite — pass --force to override.");
      return false;
    }
    if (!existing.generatedBy) {
      console.log("\n  ⚠️  exec-approvals.json exists but was not generated by EverClaw.");
      console.log("  Skipping overwrite to preserve your customizations.");
      console.log("  Pass --force to override.");
      return false;
    }
  }

  if (dryRun) {
    console.log("\n  🔍 Dry-run — no changes written.");
    console.log(`  Would write: ${approvalsPath}`);
    console.log(`  Would patch: ${configPath}`);
    return true;
  }

  // Write exec-approvals.json
  if (existsSync(approvalsPath)) {
    const backup = `${approvalsPath}.bak-${Date.now()}`;
    writeFileSync(backup, readFileSync(approvalsPath, "utf-8"));
    console.log(`  💾 Backed up → ${backup}`);
  }
  writeFileSync(approvalsPath, JSON.stringify(generated.approvals, null, 2) + "\n");
  console.log(`  ✅ Written: ${approvalsPath}`);

  // Patch openclaw.json
  if (existsSync(configPath)) {
    const config = JSON.parse(readFileSync(configPath, "utf-8"));
    const backup = `${configPath}.bak-${Date.now()}`;
    writeFileSync(backup, readFileSync(configPath, "utf-8"));
    deepMerge(config, generated.openclawPatch);
    writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
    console.log(`  ✅ Patched: ${configPath} (safeBins, strictInlineEval)`);
  } else {
    console.log(`  ⚠️  openclaw.json not found at ${configPath} — skipped safeBins patch`);
  }

  return true;
}

// ─── Status ────────────────────────────────────────────────────

function showStatus() {
  const openclawDir = getOpenClawDir();
  const approvalsPath = join(openclawDir, "exec-approvals.json");
  const configPath = join(openclawDir, "openclaw.json");

  console.log("\n♾️  EverClaw Security Status\n");

  if (!existsSync(approvalsPath)) {
    console.log("  ⚠️  No exec-approvals.json found — security tiers not configured.");
    console.log(`  Run: node scripts/security-tier.mjs --tier recommended --apply\n`);
    return;
  }

  const approvals = JSON.parse(readFileSync(approvalsPath, "utf-8"));
  const tier = approvals.tier || "custom";
  const tierLabel = approvals.tierLabel || tier;
  const generatedAt = approvals.generatedAt || "unknown";
  const generatedBy = approvals.generatedBy || "unknown";

  console.log(`  Current tier:  ${tierLabel}`);
  console.log(`  Generated by:  ${generatedBy}`);
  console.log(`  Generated at:  ${generatedAt}`);
  console.log("");

  // Count allowlist entries
  const mainAgent = approvals.agents?.main;
  if (mainAgent) {
    const allowCount = mainAgent.allowlist?.length || 0;
    const security = mainAgent.security || approvals.defaults?.security || "unknown";
    const ask = mainAgent.ask || approvals.defaults?.ask || "unknown";
    const autoSkills = mainAgent.autoAllowSkills ?? approvals.defaults?.autoAllowSkills ?? "unknown";

    console.log(`  Security mode: ${security}`);
    console.log(`  Ask mode:      ${ask}`);
    console.log(`  Auto-allow skill CLIs: ${autoSkills}`);
    console.log(`  Allowlist entries:     ${allowCount}`);
  }

  // Check openclaw.json for safeBins
  if (existsSync(configPath)) {
    const config = JSON.parse(readFileSync(configPath, "utf-8"));
    const safeBins = config.tools?.exec?.safeBins || [];
    const strictInline = config.tools?.exec?.strictInlineEval ?? "not set";
    console.log(`  SafeBins (stdin filters): ${safeBins.join(", ") || "none"}`);
    console.log(`  Strict inline eval:      ${strictInline}`);
  }

  // Summary
  console.log("");
  if (tier === "low") {
    console.log("  ✅ Read-only + dev commands: Auto-allowed");
    console.log("  🚫 Blocked: rm, docker, ssh, sudo, osascript");
    console.log("  ✋ App-gated: MOR approvals, ETH transfers, key export");
  } else if (tier === "recommended") {
    console.log("  ✅ Read-only + dev commands: Auto-allowed");
    console.log("  🚫 Blocked: rm, docker, ssh, sudo, osascript");
    console.log("  ✋ App-gated: MOR approvals, ETH transfers, key export");
    console.log("  ✋ Inline eval: Requires approval (python3 -c, node -e)");
  } else if (tier === "maximum") {
    console.log("  ✅ Read-only commands only: Auto-allowed (ls, cat, grep, find, echo, etc.)");
    console.log("  ✋ Dev tools: Require approval (node, git, curl, etc.)");
    console.log("  🚫 Blocked: rm, docker, ssh, sudo, osascript");
    console.log("  ✋ App-gated: MOR approvals, ETH transfers, key export");
    console.log("  ✋ Skill CLIs: Require explicit allowlisting");
  } else {
    console.log("  ℹ️  Custom configuration — not a standard EverClaw tier.");
  }

  console.log(`\n  Config: ${approvalsPath}`);
  console.log("");
}

// ─── CLI ───────────────────────────────────────────────────────

const args = process.argv.slice(2);

if (args.includes("--help") || args.includes("-h")) {
  console.log(`
♾️  EverClaw Security Tiers

Usage:
  node scripts/security-tier.mjs --status                    Show current tier & rules
  node scripts/security-tier.mjs --tier <name>               Dry-run tier generation
  node scripts/security-tier.mjs --tier <name> --apply       Set tier and write to disk
  node scripts/security-tier.mjs --tier <name> --force       Overwrite even if user-modified

Tiers:
  low            🟢 Fastest for daily dev (money still gated at app layer)
  recommended    🟡 Best balance — blocks deploys + dangerous ops [DEFAULT]
  maximum        🔴 Maximum protection — everything asks unless safe-listed

Options:
  --status       Show current security configuration
  --tier <name>  Set the security tier
  --apply        Write changes to disk (default is dry-run)
  --force        Overwrite existing exec-approvals.json even if user-modified
  --verbose      Show detailed binary detection output
  --help         Show this help
`);
  process.exit(0);
}

function getArg(flag) {
  const idx = args.indexOf(flag);
  return idx >= 0 && args[idx + 1] ? args[idx + 1] : null;
}

const statusMode = args.includes("--status");
const tierName = getArg("--tier");
const applyMode = args.includes("--apply");
const forceMode = args.includes("--force");
const dryRun = !applyMode;

if (statusMode) {
  showStatus();
  process.exit(0);
}

if (!tierName) {
  console.log("\n  ⚠️  No action specified. Use --status or --tier <name>.");
  console.log("  Run with --help for usage.\n");
  process.exit(1);
}

if (!VALID_TIERS.includes(tierName)) {
  console.error(`\n  ❌ Invalid tier: "${tierName}"`);
  console.error(`  Valid tiers: ${VALID_TIERS.join(", ")}\n`);
  process.exit(1);
}

// ─── Generate ──────────────────────────────────────────────────

console.log(`\n♾️  EverClaw Security — Setting tier: ${tierName}\n`);

const template = loadTierTemplate(tierName);
console.log(`  Tier:        ${template.label}`);
console.log(`  Description: ${template.description}`);
console.log(`  Platform:    ${platform()}\n`);
console.log("  Detecting binaries...\n");

const generated = generateExecApprovals(template);

console.log(`\n  Summary: ${generated.stats.found} binaries detected, ${generated.stats.missing} missing`);

if (dryRun) {
  console.log("\n  🔍 Dry-run complete — no changes written.");
  console.log("  Add --apply to write the configuration.\n");
} else {
  console.log("");
  const success = applyTier(generated, { force: forceMode, dryRun: false });
  if (success) {
    console.log("\n  Restart OpenClaw for changes to take effect:");
    console.log("    openclaw gateway restart\n");
  }
}
